name: Build Executable
permissions:
  contents: write
  
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Verify files exist
      run: |
        if (Test-Path "main.py") {
          Write-Host "Main Python file found"
        } else {
          Write-Host "ERROR: main.py not found"
          exit 1
        }
        if (Test-Path "images/icon.ico") {
          Write-Host "Icon file found"
        } else {
          Write-Host "WARNING: images/icon.ico not found, building without custom icon"
        }
      shell: powershell
      
    - name: Build executable with icon
      if: hashFiles('images/icon.ico') != ''
      run: |
        pyinstaller --onefile --hidden-import=tkinter --name "D2R AI Item Tracker" --icon=images/icon.ico --add-data "assets/fonts;assets/fonts" --add-data "images/icon-color.ico;images" main.py
      shell: cmd
      
    - name: Build executable without icon
      if: hashFiles('images/icon.ico') == ''
      run: |
        pyinstaller --onefile --hidden-import=tkinter --add-data "assets/fonts;assets/fonts" --add-data "images/icon-color.ico;images" --name "D2R AI Item Tracker" main.py
      shell: cmd
      
    - name: Verify build
      run: |
        if (Test-Path "dist/D2R AI Item Tracker.exe") {
          Write-Host "Build successful!"
          $fileSize = (Get-Item "dist/D2R AI Item Tracker.exe").Length / 1MB
          Write-Host "Executable size: $([math]::Round($fileSize, 2)) MB"
        } else {
          Write-Host "ERROR: Executable not found"
          exit 1
        }
      shell: powershell
      
    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: D2R AI Item Tracker-${{ runner.os }}
        path: "dist/D2R AI Item Tracker.exe"
        retention-days: 30
        
    - name: Upload to GitHub Release (if release)
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          "dist/D2R AI Item Tracker.exe"